excerpt_separator: <!-- excerpt -->
permalink: none
kramdown:
    syntax_highlighter_opts:
        disable: true
plugins:
    - jekyll-avatar
    - jekyll-default-layout
    - jekyll-feed
    - jekyll-github-metadata
exclude:
    - CNAME
